name: Backend CI

on:
  push:
    branches: ["desarrollo", "main"]
  pull_request:
    branches: ["desarrollo", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Pruebas con Node.js 22.x
      - name: Set up Node.js (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # Usa la versión 22.x de Node.js

      - name: Install dependencies (Node.js 22.x)
        working-directory: ./server
        run: npm install

      - name: Run tests (Node.js 22.x)
        working-directory: ./server
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test

      # Paso 3: Pruebas con Node.js 20.x
      - name: Set up Node.js (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # Usa la versión 20.x de Node.js

      - name: Install dependencies (Node.js 20.x)
        working-directory: ./server
        run: npm install

      - name: Run tests (Node.js 20.x)
        working-directory: ./server
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test
